version: 0.9.0.{build}
branches:
    only:
      - master
  
# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\iotweb

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: ARM

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# MSBuild
build:
  project: IotWeb.sln
  verbosity: normal
  
#test: off
